### ISSUE TITLE
I want to be able to bookmark a room

### ISSUE THREAD

**Issue by brazeneric** [meiao/sizematters-server#4]
Being able to include a hashed password param, a la Zoom, would be great too

**Comment by bclark0001** [comment]
I vote yes

**Comment by MikeWeinerAtBrazen** [comment]
And persist if I refresh...cuz...I refreshed and miss out on a sizing...I'm fun that way!

**Comment by meiao** [comment]
This is being moved to the ui component.

**Comment by meiao** [comment]
This was implemented but without persistence.
Please open another ticket for that functionality.
